services:
  app:
    image: highjin/front-app:latest
    container_name: front_app
    pull_policy: always
    platform: linux/amd64
    networks:
      - local

  backend-app:
    image: highjin/backend-app:latest
    pull_policy: always
    container_name: backend_app
    networks:
      - local

  nginx:
    image: nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - local

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/

networks:
  local:
